"""
send_newsletter.py
Anacruses Associates — newsletter sender via Brevo Campaigns API

Reads the approved draft from your Desktop (newsletter_draft.html),
creates a Brevo email campaign, and sends it to all subscribers on List 3.

Run this AFTER reviewing the draft generated by generate_newsletter.py:
    python send_newsletter.py

Use --dry-run to check subscriber count and subject line without sending:
    python send_newsletter.py --dry-run

Requirements:
    pip install requests

Environment variables required:
    BREVO_API_KEY   — your Brevo API key
"""

import os
import sys
import json
import argparse
import requests
from datetime import datetime
from pathlib import Path

# ─── CONFIG ──────────────────────────────────────────────────────────────────

BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')
BREVO_LIST_ID = 3
FROM_EMAIL    = 'rob.pragnell@anacruses.co.uk'
FROM_NAME     = 'Rob Pragnell — Anacruses Associates'
REPLY_TO      = 'rob.pragnell@anacruses.co.uk'
DRAFT_FILE    = Path.home() / 'Desktop' / 'newsletter_draft.html'

# ─── HELPERS ─────────────────────────────────────────────────────────────────

def get_subscriber_count():
    """Return number of active subscribers on the list."""
    url = f"https://api.brevo.com/v3/contacts/lists/{BREVO_LIST_ID}/contacts?limit=500&offset=0"
    headers = {'api-key': BREVO_API_KEY, 'accept': 'application/json'}
    r = requests.get(url, headers=headers, timeout=15)
    r.raise_for_status()
    contacts = r.json().get('contacts', [])
    return len([c for c in contacts if not c.get('emailBlacklisted', False)])


def build_subject():
    """Build the subject line with today's date."""
    today = datetime.today().strftime('%B %Y')
    return f"ISO Insights — {today}"


def create_and_send_campaign(subject, html_body):
    """
    Create and immediately send a Brevo email campaign.
    Brevo Campaigns API handles unsubscribe links automatically.
    """
    url = "https://api.brevo.com/v3/emailCampaigns"
    headers = {
        'api-key': BREVO_API_KEY,
        'Content-Type': 'application/json',
        'accept': 'application/json',
    }

    payload = {
        "name": f"ISO Insights — {datetime.today().strftime('%Y-%m-%d')}",
        "subject": subject,
        "sender": {
            "name": FROM_NAME,
            "email": FROM_EMAIL,
        },
        "replyTo": REPLY_TO,
        "htmlContent": html_body,
        "recipients": {
            "listIds": [BREVO_LIST_ID]
        },
        "scheduledAt": None,   # None = send immediately
    }

    # Step 1: Create the campaign
    print("Creating campaign in Brevo...")
    r = requests.post(url, headers=headers, json=payload, timeout=30)
    r.raise_for_status()
    campaign_id = r.json()['id']
    print(f"Campaign created (ID: {campaign_id})")

    # Step 2: Send it immediately
    print("Sending campaign to all subscribers...")
    send_url = f"https://api.brevo.com/v3/emailCampaigns/{campaign_id}/sendNow"
    r2 = requests.post(send_url, headers=headers, timeout=30)
    r2.raise_for_status()
    print("✅ Campaign sent successfully.")
    return campaign_id


# ─── MAIN ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description='Anacruses newsletter sender')
    parser.add_argument('--dry-run', action='store_true',
                        help='Show what would be sent without sending')
    args = parser.parse_args()

    print("=" * 60)
    print("Anacruses Newsletter Sender")
    print(f"Running at {datetime.now().strftime('%H:%M on %A %d %B %Y')}")
    print("=" * 60)

    # Check draft exists
    if not DRAFT_FILE.exists():
        print(f"\nERROR: No draft found at {DRAFT_FILE}")
        print("Run generate_newsletter.py first to create a draft.")
        sys.exit(1)

    # Load draft
    html_body = DRAFT_FILE.read_text(encoding='utf-8')
    print(f"\n✅ Draft loaded from: {DRAFT_FILE}")
    print(f"   Size: {len(html_body):,} characters")

    # Check API key
    if not BREVO_API_KEY:
        print("\nERROR: BREVO_API_KEY environment variable is not set.")
        print("Run:  set BREVO_API_KEY=your_key_here")
        sys.exit(1)

    # Build subject
    subject = build_subject()
    print(f"\nSubject: {subject}")

    # Get subscriber count
    print("Checking subscriber list...")
    count = get_subscriber_count()
    print(f"Active subscribers: {count}")

    if count == 0:
        print("No active subscribers — nothing to send.")
        sys.exit(0)

    if args.dry_run:
        print(f"\n[DRY RUN] Would send '{subject}' to {count} subscriber(s).")
        print("[DRY RUN] No email sent.")
        return

    # Confirm before sending
    print(f"\nReady to send '{subject}' to {count} subscriber(s).")
    confirm = input("Type YES to send: ").strip()
    if confirm != 'YES':
        print("Cancelled.")
        sys.exit(0)

    # Create and send campaign
    campaign_id = create_and_send_campaign(subject, html_body)
    print(f"\n✅ Newsletter sent. Campaign ID: {campaign_id}")
    print("You can view stats in Brevo under Campaigns → Email campaigns.")


if __name__ == '__main__':
    main()
